# Generated by Django 4.1.5 on 2023-02-10 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_creator', '0001_initial'),
        ('memoirs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoir',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompt_creator.prompt'),
        ),
    ]
