# Generated by Django 4.1.5 on 2023-01-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abc', models.CharField(max_length=100)),
            ],
        ),
    ]
