# Generated by Django 4.1.5 on 2023-02-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_ai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
