# Generated by Django 4.1.5 on 2023-02-10 07:46

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('icon', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('1', 'Gratitude'), ('2', 'Random'), ('3', 'Anxiety'), ('4', 'Introspection')], default='2', max_length=25)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
