# Generated by Django 4.1.5 on 2023-02-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='icon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('1', 'Gratitude'), ('2', 'Random'), ('3', 'Anxiety'), ('4', 'Introspection')], default='2', max_length=25),
        ),
    ]
