# Generated by Django 4.1.5 on 2023-02-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('Gratitude', 'Gratitude'), ('Random', 'Random'), ('Anxiety', 'Anxiety'), ('Introspection', 'Introspection')], default='Random', max_length=25),
        ),
    ]
