# Generated by Django 4.1.5 on 2023-02-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_creator', '0002_alter_prompt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='example_text',
            field=models.CharField(default='Write Something...', max_length=500, null=True),
        ),
    ]
